# -*- coding: utf-8 -*-
"""string constants.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_9ewclclNjPp1IBHAqTLSuw4M41nSGl
"""

import string

letters = string.ascii_letters
letters

lowercase = string.ascii_lowercase
lowercase

uppercase = string.ascii_uppercase 
uppercase

digits = string.digits
digits

# 16진법
hexdigits = string.hexdigits
hexdigits

# 0 ~ 15까지일텐데 대문자는 뭘까...

octdigits = string.octdigits
octdigits

punctuation = string.punctuation
punctuation

# digits + ascii_letters + punctuation + whitespace.
printable = string.printable
printable

# characters space, tab, linefeed, return, formfeed, and vertical tab
whitespace = string.whitespace
whitespace