-- 가격이 제일 비싼 식품의 정보 출력하기
SELECT *
    FROM FOOD_PRODUCT
    WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);


-- 가장 비싼 상품 구하기
SELECT MAX(PRICE) as MAX_PRICE FROM PRODUCT;

-- 최댓값/최솟값/동물수 구하기
SELECT MAX(DATETIME) as 시간 FROM ANIMAL_INS;
SELECT MIN(DATETIME) as 시간 FROM ANIMAL_INS;
select count(ANIMAL_ID) from ANIMAL_INS;

-- 중복 제거하기
-- SELECT DISTINCT COUNT(NAME) as 컬럼이름노상관 FROM ANIMAL_INS;
SELECT COUNT(DISTINCT NAME) as 컬럼이름노상관 FROM ANIMAL_INS;
